### ISSUE TITLE
version of pytorch and torchvision missmatch

### ISSUE THREAD

**Issue by crankyz** [Xiaojiu-z/Stable-Hair#16]
ERROR: Cannot install torch==2.2.2 and torchvision==0.16.2+cu118 because these package versions have conflicting dependencies.

**Comment by Xiaojiu-z** [comment]
> ERROR: Cannot install torch==2.2.2 and torchvision==0.16.2+cu118 because these package versions have conflicting dependencies.

Well, I don't know why my environment works well. Anyway, using the latest torch/torchvision may help you.

**Comment by sagielightricks** [comment]
same, it doesn't work together. I assume you may have manually installed some packages once in a certain combination that works but the versions you selected in the `requirements.txt` do not reflect them. That's pretty much guaranteed since, when trying to setup this project from scratch, there's a ton of conflicts. I'd advise you to a new environment and test it yourself:

```
ERROR: Cannot install -r requirements.txt (line 134), -r requirements.txt (line 17), -r requirements.txt (line 4), -r requirements.txt (line 57), -r requirements.txt (line 93) and torch==2.2.2+cu118 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==2.2.2+cu118
    accelerate 1.0.1 depends on torch>=1.10.0
    bitsandbytes 0.44.1 depends on torch
    kornia 0.7.3 depends on torch>=1.9.1
    peft 0.11.1 depends on torch>=1.13.0
    torchvision 0.16.2+cu118 depends on torch==2.1.2
```
